repos:
  # ----------------------------------------------------
  # 1. 基础检查（Git 提交和通用文件）
  # ----------------------------------------------------
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace         # 移除行尾空格
      - id: end-of-file-fixer           # 确保文件以空行结束
      - id: check-yaml                  # 检查 YAML 文件语法
        args: ['--unsafe']              # 允许自定义标签
      - id: check-merge-conflict        # 检查合并冲突标记
      - id: debug-statements            # 检查调试语句
      - id: check-toml                  # 检查 TOML 文件语法 (pyproject.toml)
      - id: check-json                  # 检查 JSON 文件语法
      - id: mixed-line-ending           # 检查行结束符
      - id: detect-private-key          # 检查是否意外提交了私钥
      - id: check-added-large-files     # 阻止提交大文件
        args: ['--maxkb=10000']         # 限制10MB
      - id: check-case-conflict         # 检查文件名大小写冲突
  # ----------------------------------------------------
  # 2. 格式化工具 (Formatting)
  # ----------------------------------------------------
  # Black: Python 黑色格式化工具 (非侵入式代码风格)
  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
        args: ["--line-length=100"] # 推荐行长 100

  # isort: 导入排序工具 (必须放在 black 之后，防止冲突)
  - repo: https://github.com/PyCQA/isort
    rev: 7.0.0
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black", "--line-length=100"] # 使用 black 兼容模式

  # ----------------------------------------------------
  # 3. 静态分析与质量工具 (Linting & Quality)
  # ----------------------------------------------------
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.2
    hooks:
      - id: ruff                     # Python代码检查
        args: [--fix, --exit-non-zero-on-fix]
        types_or: [python, pyi, jupyter]
      - id: ruff-format             # Python代码格式化
        types_or: [python, pyi, jupyter]

  # 可选: 添加类型检查 (如需要可取消注释)
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.8.0
  #   hooks:
  #     - id: mypy
  #       additional_dependencies: [types-all]
  #       args: [--ignore-missing-imports]

  # 可选: 安全检查 (如需要可取消注释)
  # - repo: https://github.com/PyCQA/bandit
  #   rev: '1.7.5'
  #   hooks:
  #     - id: bandit
  #       args: ['-r', 'src/', '-f', 'json', '-o', 'bandit-report.json']
