repos:
  # ----------------------------------------------------
  # 1. 基础检查（Git 提交和通用文件）
  # ----------------------------------------------------
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml                  # 检查 YAML 文件语法
        args: ['--unsafe']              # 允许自定义标签
      - id: check-merge-conflict        # 检查合并冲突标记
      - id: check-toml                  # 检查 TOML 文件语法 (pyproject.toml)
      - id: check-json                  # 检查 JSON 文件语法
      - id: detect-private-key          # 检查是否意外提交了私钥
      - id: check-added-large-files     # 阻止提交大文件
        args: ['--maxkb=10000']         # 限制10MB
      - id: check-case-conflict         # 检查文件名大小写冲突

  # ----------------------------------------------------
  # 2. 格式化与质量工具 (Linting & Quality)
  # ----------------------------------------------------
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.2
    hooks:
      - id: ruff                     # Python代码检查
        args: [--fix]
      - id: ruff-format             # Python代码格式化

  # 3. 静态类型检查
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy

